### ISSUE TITLE
CPP14 sizeof return always 1

### ISSUE THREAD

**Issue by llnns** [UnicoenProject/unicoen.ts#57]
Hello,

I've been using PLIVET (https://github.com/RYOSKATE/PLIVET) and I noticed that `sizeof` always return 1 independent of the type.

I also notice that there is this function here that always return 1 and there is a following commented code:

https://github.com/UnicoenProject/unicoen.ts/blob/8e5768f4ce08677a7a914c29811bd76dea547c75/src/interpreter/CPP14/CPP14Engine.ts#L83-L95

Thanks,

**Comment by RYOSKATE** [comment]
Thank you for your comment!
unicoen.ts did not give the correct type-related size for values on memory.
Now, we implemented the mechanism (v0.5.0) and `sizeof` returns the correct size for simple usage.

**Comment by llnns** [comment]
Thanks!
